
(defun part-1 (filename)
  (let ((score 0))
    (dolist (line (uiop:read-file-lines filename))
      (cond  ((equal line "A X") (incf score 4))
	     ((equal line "A Y") (incf score 8))
	     ((equal line "A Z") (incf score 3))
	     ((equal line "B X") (incf score 1))
	     ((equal line "B Y") (incf score 5))
	     ((equal line "B Z") (incf score 9))
	     ((equal line "C X") (incf score 7))
	     ((equal line "C Y") (incf score 2))
	     ((equal line "C Z") (incf score 6))
	     (t (incf score 0))))
    score))

(defun part-2 (filename)
  (let ((score 0))
    (dolist (line (uiop:read-file-lines filename))
      (cond  ((equal line "A X") (incf score 3))
	     ((equal line "A Y") (incf score 4))
	     ((equal line "A Z") (incf score 8))
	     ((equal line "B X") (incf score 1))
	     ((equal line "B Y") (incf score 5))
	     ((equal line "B Z") (incf score 9))
	     ((equal line "C X") (incf score 2))
	     ((equal line "C Y") (incf score 6))
	     ((equal line "C Z") (incf score 7))
	     (t (incf score 0))))
    score))

(part-1 "day2.input")
(part-2 "day2.input")
