[package]
name = "aoc-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day-one = { path = "../day-one" }
day-two = { path = "../day-two" }
day-three = { path = "../day-three" }
